#!/usr/bin/env python3
"""
Contains:
    Classes
    =======
    Cache - Wrapper to enable caching using redis
"""
import redis
import uuid
from typing import Any, Awaitable, Callable, Type, Union


class Cache:
    """Provides caching using redis"""
    def __init__(self) -> None:
        """Initializes a newly created instance"""
        self._redis = redis.Redis()
        self._redis.flushdb()

    def store(self, data: Union[str, bytes, int, float]) -> str:
        """
        Stores data to the client with a random key
        generated by uuid

        Args:
            data (str | bytes | int | float) : The data to store

        Returns:
            (str): The randomly generated key used to store the data
        """
        key = uuid.uuid4()
        self._redis.set(str(key), data)
        return (str(key))

    def get(self, key: str, fn: Any = None) -> Any:
        """
        Receives a key and returns the value stored after using the
        given callback function (if given) to convert the bytes that
        redis returns by default
        """
        val = self._redis.get(key)
        if val:
            if fn:
                return fn(val)
        return (val)

    def get_int(self, key: str) -> Union[int, None]:
        """
        Gets a value from redis server and attempts to convert to
        int using the get method with the int() function passed as
        callback
        """
        return self.get(key, int)

    def get_str(self, key: str) -> Union[str, None]:
        """
        Gets a value from redis server and attempts to convert to
        str using the get method with the .decode('utf-8') function
        passed as lambda callback
        """
        return self.get(key, lambda val: val.decode("utf-8"))
